[features]
seeds = false
skip-lint = false
[programs.localnet]
demo_project = "9CdHEqVd7ZM5Hk34MPCPNG6NPA5QiaxFV9awc57DfSQH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/ubuntu/Workspace/localnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
